version: '3.3'

services:
    frontend:
        image: frontend:stable
        build:
            context: ./Dockerfiles
            dockerfile: ./Frontend.dockerfile
        volumes: 
            - ./Frontend/:/code
        ports:
            - 8080:8080

    backend:
        image: backend:stable
        build:
            context: ./Dockerfiles
            dockerfile: ./Backend.dockerfile
        volumes: 
            - ./Backend/:/code
        ports:
            - 8081:8081
    
    database:
        image: mysql:5
        volumes: 
            - ./Dockerfiles/Resources/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: todo
            MYSQL_DATABASE: todo
            MYSQL_USER: todo
            MYSQL_PASSWORD: todo
        expose:
            - 3306